name: Reusable App Build

on:
  workflow_call:

    inputs:

      cloud-provider:
        required: true
        type: string

      registry-url:
        required: true
        type: string

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build Application
        working-directory: app
        run: mvn clean package

      - name: Azure Login
        if: inputs.cloud-provider == 'azure'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Container Registry Login
        if: inputs.cloud-provider == 'azure'
        run: |
          az acr login --name ${{ secrets.TF_VAR_acr_name }}

      - name: Configure AWS Credentials
        if: inputs.cloud-provider == 'aws'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: AWS ECR Login
        if: inputs.cloud-provider == 'aws'
        run: |
          aws ecr get-login-password \
          | docker login \
            --username AWS \
            --password-stdin \
            ${{ inputs.registry-url }}

      - name: Docker Build
        run: |
          docker build \
            -t ${{ inputs.registry-url }}/myapp:latest \
            ./app

      - name: Docker Push
        run: |
          docker push \
            ${{ inputs.registry-url }}/myapp:latest