name: Reusable App Build

on:
  workflow_call:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Setup Java

        uses: actions/setup-java@v4

        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build Application

        working-directory: app

        run: mvn clean package

      - name: Azure Login

        uses: azure/login@v2

        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Container Registry Login

        run: |
          az acr login --name ${{ secrets.TF_VAR_acr_name }}

      - name: Docker Build

        run: |
          docker build \
            -t ${{ secrets.TF_VAR_acr_name }}.azurecr.io/myapp:latest \
            ./app

      - name: Docker Push

        run: |
          docker push \
            ${{ secrets.TF_VAR_acr_name }}.azurecr.io/myapp:latest