name: Reusable Registry Login

on:
  workflow_call:
    inputs:
      registry-url:
        required: true
        type: string

      registry-username:
        required: true
        type: string

      registry-password:
        required: true
        type: string

jobs:
  registry-login:
    runs-on: ubuntu-latest

    steps:
      - name: Docker Login
        run: |
          echo "${{ inputs.registry-password }}" | docker login \
            ${{ inputs.registry-url }} \
            -u "${{ inputs.registry-username }}" \
            --password-stdin