name: Reusable Security Scan

on:
  workflow_call:

jobs:

  security:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Run Trivy Filesystem Scan

        uses: aquasecurity/trivy-action@0.20.0

        with:
          scan-type: fs
          scan-ref: .