name: Reusable Terraform Apply

on:
  workflow_call:

    inputs:

      cloud-provider:
        required: true
        type: string

      working-directory:
        required: true
        type: string

jobs:

  apply:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:

      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Azure Login

        if: inputs.cloud-provider == 'azure'

        uses: azure/login@v2

        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init -reconfigure -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false