#cloud-config

package_update: true
package_upgrade: true

packages:
  - docker.io
  - curl
  - git
  - unzip
  - awscli
  
 bootcmd:
  - mkdir -p /home/${admin_username}/app/contracts/runtime
  - mkdir -p /home/${admin_username}/app/contracts/observability
  - mkdir -p /home/${admin_username}/app/contracts/security
  - mkdir -p /home/${admin_username}/app/scripts/runtime/providers 

write_files:

  - path: /home/${admin_username}/.docker/config.json
    permissions: '0600'
    owner: ${admin_username}:${admin_username}
    content: |
      {}

  - path: /home/${admin_username}/app/contracts/runtime/deploy.sh
    permissions: '0755'
    owner: ${admin_username}:${admin_username}
    content: |
${indent(6, deploy_sh)}

  - path: /home/${admin_username}/app/scripts/runtime/providers/azure.sh
    permissions: '0755'
    owner: ${admin_username}:${admin_username}
    content: |
${indent(6, azure_provider_sh)}

  - path: /home/${admin_username}/app/scripts/runtime/providers/aws.sh
    permissions: '0755'
    owner: ${admin_username}:${admin_username}
    content: |
${indent(6, aws_provider_sh)}

runcmd:
  - systemctl enable docker
  - systemctl start docker

  - usermod -aG docker ${admin_username}

  - chown -R ${admin_username}:${admin_username} /home/${admin_username}/app