name: Multi Cloud Application Delivery

on:
  workflow_dispatch:

    inputs:

      cloud:
        required: true
        type: choice
        options:
          - azure
          - aws

concurrency:
  group: app-${{ github.event.inputs.cloud }}
  cancel-in-progress: false

jobs:

  outputs:

    uses: ./.github/workflows/read-outputs.yml

    with:
      working-directory: terraform/environments/${{ github.event.inputs.cloud }}/prod
      cloud-provider: ${{ github.event.inputs.cloud }}

    secrets: inherit

  build:

    needs: outputs

    uses: ./.github/workflows/app-build.yml

    with:
      cloud-provider: ${{ github.event.inputs.cloud }}
      registry-url: ${{ needs.outputs.outputs.registry_url }}

    secrets: inherit

  security:

    needs: build

    uses: ./.github/workflows/security-scan.yml

    secrets: inherit

  deploy:

    needs:
      - outputs
      - build
      - security

    uses: ./.github/workflows/app-deploy.yml

    with:

      cloud-provider: ${{ github.event.inputs.cloud }}

      vm-ip: ${{ needs.outputs.outputs.vm_ip }}

      ssh-user: ${{ needs.outputs.outputs.ssh_user }}

      registry-url: ${{ needs.outputs.outputs.registry_url }}

      registry-username: ${{ needs.outputs.outputs.registry_username }}

    secrets: inherit


