name: Reusable App Build

on:
  workflow_call:

    inputs:
      cloud-provider:
        required: true
        type: string

      registry-server:
        required: true
        type: string

      repository-name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build App
        working-directory: app
        run: mvn clean package

      - name: Validate inputs
        shell: bash
        run: |
          if [ -z "${{ inputs.registry-server }}" ]; then
            echo "❌ registry-server EMPTY"
            exit 1
          fi

      - name: AWS Login
        if: inputs.cloud-provider == 'aws'
        shell: bash
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login \
            --username AWS \
            --password-stdin \
            "${{ inputs.registry-server }}"

      - name: Build Docker Image
        run: |
          IMAGE="${{ inputs.registry-server }}/${{ inputs.repository-name }}"
          docker build -t $IMAGE:latest ./app

      - name: Push Docker Image
        run: |
          IMAGE="${{ inputs.registry-server }}/${{ inputs.repository-name }}"
          docker push $IMAGE:latest