name: Multi Cloud Application Delivery

on:
  workflow_dispatch:

    inputs:

      cloud:
        required: true
        type: choice
        options:
          - azure
          - aws

concurrency:
  group: app-${{ github.event.inputs.cloud }}
  cancel-in-progress: false

jobs:

  outputs:

    uses: ./.github/workflows/read-outputs.yml

    with:
      working-directory: terraform/environments/${{ github.event.inputs.cloud }}/prod
      cloud-provider: ${{ github.event.inputs.cloud }}

    secrets: inherit


  debug:

    needs: outputs

    runs-on: ubuntu-latest

    steps:

      - name: Show reusable workflow outputs
        run: |
          echo "======================================="
          echo "OUTPUTS RECEIVED FROM read-outputs.yml"
          echo "======================================="
          echo "VM_IP='${{ needs.outputs.vm_ip }}'"
          echo "REGISTRY_SERVER='${{ needs.outputs.registry_server }}'"
          echo "REPOSITORY_NAME='${{ needs.outputs.repository_name }}'"
          echo "REGISTRY_USERNAME='${{ needs.outputs.registry_username }}'"
          echo "REGISTRY_PASSWORD='***'"
          echo "SSH_USER='${{ needs.outputs.ssh_user }}'"
          echo "======================================="


  build:

    needs:
      - outputs
      - debug

    uses: ./.github/workflows/app-build.yml

    with:
      cloud-provider: ${{ github.event.inputs.cloud }}
      registry-server: ${{ needs.outputs.registry_server }}
      repository-name: ${{ needs.outputs.repository_name }}

    secrets: inherit


  security:

    needs: build

    uses: ./.github/workflows/security-scan.yml

    secrets: inherit


  deploy:

    needs:
      - outputs
      - build
      - security

    uses: ./.github/workflows/app-deploy.yml

    with:

      cloud-provider: ${{ github.event.inputs.cloud }}

      vm-ip: ${{ needs.outputs.vm_ip }}

      ssh-user: ${{ needs.outputs.ssh_user }}

      registry-url: ${{ needs.outputs.registry_server }}/${{ needs.outputs.repository_name }}

      registry-username: ${{ needs.outputs.registry_username }}

      registry-password: ${{ needs.outputs.registry_password }}

    secrets: inherit