name: Reusable Terraform Plan

on:
  workflow_call:

    inputs:

      cloud-provider:
        required: true
        type: string

jobs:

  plan:

    runs-on: ubuntu-latest

    env:

      TF_WORKING_DIR: ${{ inputs.cloud-provider == 'aws' && 'terraform/stacks/aws/app-platform' || 'terraform/stacks/azure/app-platform' }}

      TF_VAR_name_prefix: ${{ vars.NAME_PREFIX }}
      TF_VAR_instance_type: ${{ vars.TF_VAR_INSTANCE_TYPE }}
      TF_VAR_repository_name: ${{ vars.TF_VAR_REPOSITORY_NAME }}
      TF_VAR_aws_region: ${{ vars.TF_VAR_AWS_REGION }}
      TF_VAR_vpc_cidr: ${{ vars.VPC_CIDR }}
      TF_VAR_subnet_cidr: ${{ vars.SUBNET_CIDR }}

      TF_VAR_tags: >
        {
          "Project":"Enterprise",
          "Environment":"Production",
          "ManagedBy":"Terraform"
        }

    defaults:

      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:

      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Configure AWS Credentials
        if: inputs.cloud-provider == 'aws'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Azure Login
        if: inputs.cloud-provider == 'azure'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: |
          terraform init \
            -reconfigure \
            -input=false \
            -backend-config="bucket=${{ vars.TF_BACKEND_BUCKET }}" \
            -backend-config="key=${{ vars.TF_BACKEND_KEY }}" \
            -backend-config="region=${{ secrets.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ vars.TF_BACKEND_LOCK_TABLE }}"

      - name: Show Remote State
        run: terraform state pull

      - name: Show Terraform State
        run: terraform state list

      - name: Terraform Format
        run: terraform fmt -check -diff -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -no-color